'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminEvalMonthlyReport

    '''<summary>
    '''buttonaddon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonaddon2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''testUser1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents testUser1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''testUser2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents testUser2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''testUer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents testUer3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''testUer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents testUer4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''studentTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentTable As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''nameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents close As Global.System.Web.UI.WebControls.Button
End Class
