'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FacultyEvalAttendance
    
    '''<summary>
    '''RBFEQ1S2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ1S2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RBFEQ1S3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ1S3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RBFEQ3S1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S1 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RBFEQ3S2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S2 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RBFEQ3S3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S3 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RBFEQ3S4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S4 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RBFEQ3S5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3S5 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RBFEQ3SNA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBFEQ3SNA As Global.System.Web.UI.WebControls.RadioButton
End Class
